name: Node.js CI
on:
 push:
 branches: [ main ]
 pull_request:
 branches: [ main ]
jobs:
 build:
 runs-on: ubuntu-latest
 strategy:
 matrix:
 node-version: [16.x]
 # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 steps:
 - uses: actions/checkout@v2
 - name: Use Node.js
 uses: actions/setup-node@v2
 with:
 node-version: “16.x”
 - name: Install dependencies
 run: npm install
 - name: Run test
 run: npm test
 - name: Check Job Status status and fail if they are red
 if: env.WORKFLOW_CONCLUSION == ‘failure’
 run: exit 1
